[package]
name = "our-package-manager"
url = "https://github.com/Kapybara48/our-package-manager.git"
git_clone_depth = 1
git_clone_branch = "main"
makefile = "Makefile"
makefile_target = "install"
install_script = ""
