name = "our-package-manager"
url = "https://github.com/Kapybara48/our-package-manager.git"
gitCloneDepth = 1
gitCloneBranch = "main"
makefile = "Makefile"
makefileTarget = "install"
installScript = ""
