Name = "our-package-manager"
URL = "https://github.com/Kapybara48/our-package-manager.git"
GitCloneDepth = 1
GitCloneBranch = "main"
Makefile = "Makefile"
MakefileTarget = "install"
InstallScript = ""
